on:
  # Настройка запуска процесса на каждое событие push
  workflow_dispatch:
  push:
    branches: main
# Название процесса
name: Quarto Publish

# Задачи, которые необходимо выполнить
jobs:
  # Задача сборки и публикации проекта
  build-deploy:
    # Указание, что запускать нужно на ubuntu последней версии
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    # Описание необходимых шагов сборки
    steps:
      # Установка необходимых пакетов в Ubuntu
      - name: Install libcurl
        run: sudo apt install -y libcurl4-openssl-dev libfontconfig1-dev libcairo2-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libgdal-dev
      # Получение актуального состояния репозитория
      # https://github.com/actions/checkout/tree/main
      - name: Check out repository
        uses: actions/checkout@v4
      # Установка Quarto
      # https://github.com/quarto-dev/quarto-actions
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2.1.6
      # Установка R
      # https://github.com/r-lib/actions
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
      # Установка необходимых для нашего проекта зависимостей
      # https://github.com/r-lib/actions
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      # Компиляция и публикация дашборда
      # https://github.com/quarto-dev/quarto-actions
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2.1.6
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}